### ISSUE TITLE
Unusable -s/--summary option

### ISSUE THREAD

**Issue by hcpl** [imp/cargo-info#4]
Because `cargo info --help` says `Report the crates.io summary information` about `-s, --summary`, we don't pass crate name:
```sh
$ cargo info -s
error: The following required arguments were not provided:
    <crate>...

USAGE:
    cargo info <crate>... --summary

For more information try --help
```

Oh, OK, let's try to pass it:
```sh
$ cargo info -s error_chain
error: The argument '<crate>...' cannot be used with '--summary'

USAGE:
    cargo info <crate>... --summary

For more information try --help
```

Seems like some conflicting rules are contradicting each other.

**Comment by imp** [comment]
Thanks for spotting this. In fact ```-s/--summary``` was a work in progress that never made it into the master branch. However the flag itself was unintentionally added by a mismerge.
Instead of merging your commit I'd rather remove this option altogether until it is done.

And sorry for taking long time to react - I was on vacation w/o internet

**Comment by hcpl** [comment]
Oh, okay. I guess this issue can be closed then
